### ISSUE TITLE
Official ReasonML binding

### ISSUE THREAD

**Issue by dangdennis** [FormidableLabs/next-urql#12]
Hi Parker,

Are you considering shipping official Reason binding for next-urql?

**Comment by parkerziegler** [comment]
👋 Hey Dennis! I wasn't necessarily planning on it, especially since it'd be such a small binding and probably more work than its worth to get a whole repo set up for it. But I could include a section in the README with the binding I use for it, which seems to be working pretty well. If I included that here and in the docs for `reason-urql`, would that be a suitable middle ground?

**Comment by dangdennis** [comment]
Yes! Thank you so much. That really is more than enough.
