### ISSUE TITLE
cacheExchange with next-urql

### ISSUE THREAD

**Issue by n44ps** [FormidableLabs/next-urql#27]
Hello !

I've been using `urql` `next-urql` & `@urql/exchange-graphcache` with `NextJS`.
I use the `withUrqlClient` HOC only on pages that needs SSR but I would like to use optimistic response and I cannot make it work.
At first I wrapped the `_app.tsx` with a `<Provider client={client}></Provider>` and still used the `withUrqlClient` HOC. But then components inside the SSR Page would not benefit from the client side optimistic resolvers.

```js
const client = createClient({
  url: process.env.API_ENDPOINT as string,
  exchanges: [
    dedupExchange,
    cacheExchange({
      optimistic: {
        myMutation: (variables) => ({
          ...variables,
          __typename: 'MyTypeName',
        }),
      },
    }),
    fetchExchange,
  ],
  fetchOptions: {
    credentials: 'include',
  },
});

class MyApp extends App {
  render(): JSX.Element {
    const { Component, pageProps } = this.props as any;
    return (
      <>
          <Provider value={client}>
            <Component {...pageProps} />
          </Provider>
      </>
    );
  }
}

export default MyApp;
```

```js
const Page = () => (
   <>
      ...
      <MyMutationComponent />
   </>
)

// I tried to use the same as the client side urql
export default withUrqlClient(ctx => {
  url: process.env.API_ENDPOINT as string,
  exchanges: [
    dedupExchange,
    cacheExchange({
      optimistic: {
        myMutation: (variables) => ({
          ...variables,
          __typename: 'MyTypeName',
        }),
      },
    }),
    fetchExchange,
  ],
  fetchOptions: {
    headers: ctx?.req?.headers,
    credentials: 'include',
  },
})(Page);
```

Obviously if I remove the HOC, the client side urql will work properly.
If I keep the HOC but also keep the Provider that wraps `_app.tsx`, it still doesn't work because I guess my `<MyMutationComponent />` uses the provider from the `withUrqlClient` HOC.

Should I wrap the component doing the mutation with a client side urql provider ?

Thank you,

n44ps

**Comment by parkerziegler** [comment]
Hey @n44ps, apologies for the late reply. I think a big part of the issue here may be that you're not using the `mergeExchanges` argument that's part of `next-urql`'s API: https://github.com/FormidableLabs/next-urql#mergeexchanges-optional.

The idea with `mergeExchanges` is that it allows you to customize your exchanges while ensuring that the required `ssrExchange` actually gets into that array. For most users, they don't need or want to think about adding the `ssrExchange` – they just want things to work. But if you're opting in to additional exchanges beyond the default, this is the place to add those. In your example above, that'd work something like the following:

```typescript
export default withUrqlClient(
  ctx => ({
    url: process.env.API_ENDPOINT as string,
    fetchOptions: {
      headers: ctx?.req?.headers,
      credentials: 'include',
    },
  }),
  ssrEx => {
    return [
      dedupExchange,
      cacheExchange({
        optimistic: {
          myMutation: (variables) => ({
            ...variables,
            __typename: 'MyTypeName',
          }),
        },
      }),
      ssrEx,
      fetchExchange,
    ],
  }
)(Page);
```

Let me know if that wasn't clear from the docs, and I can add additional notes to explain things. Going to close this for now, but feel free to reopen if this isn't working as expected.
